# Generated by Django 2.2.16 on 2022-05-15 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220513_1541'),
    ]

    operations = [
    ]
