# Generated by Django 2.2.16 on 2022-05-21 09:55

import reviews.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20220519_0138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='titlegenre',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveIntegerField(validators=[reviews.validators.validate_score]),
        ),
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(db_index=True, related_name='titles', through='reviews.TitleGenre', to='reviews.Genre'),
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveIntegerField(db_index=True, validators=[reviews.validators.validate_year]),
        ),
    ]
