# Generated by Django 2.2.16 on 2022-05-21 10:41

import reviews.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_title_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[reviews.validators.validate_score]),
        ),
    ]
